# Generated by Django 6.0.2 on 2026-02-17 01:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerprofile',
            name='academic_certificates',
            field=models.FileField(blank=True, help_text='Academic qualifications and certificates.', null=True, upload_to=accounts.models.provider_academic_path),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='identification_documents',
            field=models.FileField(blank=True, help_text='ID card, passport, or other government-issued identification.', null=True, upload_to=accounts.models.provider_id_path),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='professional_licence',
            field=models.FileField(blank=True, help_text='Proof of registration with Medical or Pharmacy Council.', null=True, upload_to=accounts.models.provider_document_path),
        ),
    ]
