# Generated by Django 6.0.2 on 2026-02-21 01:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_provider_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (optional).', null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
    ]
