# Generated by Django 6.0.2 on 2026-02-17 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_call'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text Message'), ('PRESCRIPTION', 'Prescription')], default='TEXT', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='prescriptions.prescription'),
        ),
    ]
