# Generated by Django 6.0.2 on 2026-02-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('messaging', '0003_message_message_type_message_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('VIDEO', 'Video Call'), ('AUDIO', 'Audio Call')], default='VIDEO', max_length=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('NOTIFIED', 'Notified'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('room_id', models.CharField(help_text='Unique room identifier for the scheduled call.', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='appointments.appointment')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='messaging.conversation')),
            ],
            options={
                'verbose_name': 'Scheduled Call',
                'verbose_name_plural': 'Scheduled Calls',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
