# Generated by Django 6.0.2 on 2026-02-23 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.scheduledcall'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CALL_INVITE', 'Call Invite'), ('CALL_MISSED', 'Call Missed'), ('MESSAGE', 'Message'), ('PRESCRIPTION', 'Prescription'), ('SCHEDULED_CALL', 'Scheduled Call')], max_length=20),
        ),
    ]
