# Generated by Django 6.0.2 on 2026-02-24 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('consultations', '0001_initial'),
        ('messaging', '0006_notification_scheduled_call_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('CALL_INVITE', 'Call Invite'), ('CALL_MISSED', 'Call Missed'), ('MESSAGE', 'Message'), ('PRESCRIPTION', 'Prescription'), ('SCHEDULED_CALL', 'Scheduled Call'), ('APPOINTMENT_REMINDER', 'Appointment Reminder'), ('PRESCRIPTION_UPDATE', 'Prescription Update'), ('SCHEDULED_CONSULTATION', 'Scheduled Consultation')], max_length=30),
        ),
    ]
