# Generated by Django 6.0.3 on 2026-03-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_notification_appointment_notification_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversation thread this notification belongs to (for MESSAGE notifications).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='messaging.conversation'),
        ),
    ]
