# Generated by Django 6.0.3 on 2026-03-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sickness_type',
            field=models.CharField(choices=[('general', 'General / Not Sure'), ('cardiology', 'Heart & Cardiovascular'), ('dermatology', 'Skin, Hair & Nails'), ('endocrinology', 'Diabetes & Hormonal'), ('ent', 'Ear, Nose & Throat'), ('gastroenterology', 'Digestive & Stomach'), ('gynecology', "Women's Health & Gynecology"), ('mental_health', 'Mental Health & Psychiatry'), ('neurology', 'Brain & Nervous System'), ('oncology', 'Cancer & Oncology'), ('ophthalmology', 'Eye & Vision'), ('orthopedics', 'Bones, Joints & Muscles'), ('pediatrics', "Children's Health"), ('pulmonology', 'Lungs & Respiratory'), ('urology', 'Urinary & Kidney'), ('other', 'Other')], default='general', help_text='Type of condition to match with the right specialist.', max_length=50),
        ),
    ]
