# Generated by Django 6.0.3 on 2026-03-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_sickness_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sickness_other',
            field=models.CharField(blank=True, help_text="Describe the condition when 'Other' is selected.", max_length=255),
        ),
    ]
